### ISSUE TITLE
Improve navbar design of webpage

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#1]
![Screenshot (175)](https://user-images.githubusercontent.com/56196640/123571531-0cad4a80-d7e8-11eb-841d-d60f91748652.png)

Apply on all pages

**Comment by K-jais** [comment]
Please assign this issue to me. I can redesign this navbar and make it look a lot better than before.

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DevIncept will commence from 10th July.

**Comment by K-jais** [comment]
Ok sir.

**Comment by tany1014** [comment]
i will develop a nav bar which fits to your website and can solve your issue @QAZIMAAZARSHAD

**Comment by tjanhvi** [comment]
Can I redesign the navbar? ..  I would like to do this..

**Comment by QAZIMAAZARSHAD** [comment]
> Can I redesign the navbar? .. I would like to do this..

This issue is already assigned.

**Comment by tjanhvi** [comment]
> > Can I redesign the navbar? .. I would like to do this..
> 
> This issue is already assigned.

okay

**Comment by satyampgt4** [comment]
@tany1014 any updates ...?

**Comment by LeeSinYung** [comment]
May I request to improve  the navbar? Only the navbar at the homepage had been modify. I would like to modify the others pages like faq and so on.

**Comment by tjanhvi** [comment]
> > Can I redesign the navbar? .. I would like to do this..
> 
> This issue is already assigned.

Any updates
????

**Comment by QAZIMAAZARSHAD** [comment]
@tjanhvi let's wait for @tany1014 reply for a few more hours.

If we receive no response then I will assign you.
