### ISSUE TITLE
Create a "Baby & Kids" page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#10]

**Comment by Baba-Yaga-1** [comment]
I am a participant of DevIncept. Can I work on this issue ?

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DCP will start from 10th July.

**Comment by Baba-Yaga-1** [comment]
Do I have to follow a certain theme for this page ?

**Comment by QAZIMAAZARSHAD** [comment]
Just follow the color theme.

And implement any idea for styling, but the footer and header should be the same.
We will adopt the best theme for all the pages later when other pages are also created.

**Comment by Baba-Yaga-1** [comment]
Should I make a static page for now ?

**Comment by QAZIMAAZARSHAD** [comment]
> Should I make a static page for now ?

Yess, refer to some websites and adopt their design if you want.

**Comment by Baba-Yaga-1** [comment]
Okay, sure.

**Comment by Baba-Yaga-1** [comment]
I have made the page, can you check it.

![babyKids](https://user-images.githubusercontent.com/56999749/125188660-2f147e80-e252-11eb-8ab1-5169788a3663.JPG)

**Comment by QAZIMAAZARSHAD** [comment]
Share website link.

Also add some details like color, brand, price.
Also, add footer and header.

**Comment by Baba-Yaga-1** [comment]
Okay, sure.
I will make the changes and share the link.
I haven't changed the header and footer.

![babyKids2](https://user-images.githubusercontent.com/56999749/125189030-e6f65b80-e253-11eb-9134-144769d8a953.JPG)

**Comment by Baba-Yaga-1** [comment]
Can you check this ?
I have made the changes and I haven't changed the header and footer.

https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

**Comment by QAZIMAAZARSHAD** [comment]
The slider image is very large.

Arrange cards properly, left and right margins should be equal.

Fetch upstream also your repo is not updated.

Align nav bar properly.

**Comment by Baba-Yaga-1** [comment]
Can you check this ? I have made the changes.

https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

**Comment by QAZIMAAZARSHAD** [comment]
No still not correct.

First, fetch upstream keep your repo updated.

Reduce the height and increase the width to 100% of the slideshow.
Also, replace slideshow images, use modelling kids.
Add three cards in one row.

**Comment by Baba-Yaga-1** [comment]
I did update the repo.
So I need to replace the slideshows with cards or I just need to chnge the pictures ?
Also does this page also have to show the links to other pages like clothes, furniture etc ?

**Comment by QAZIMAAZARSHAD** [comment]
Just adjust the size of the slideshow.
Change images in the slideshow.
By cards, I meant products like jackets, shoes, etc. there are two cards in each row and plenty of margin on the right side.
Decrease the size of these cards and add 3 in each row.
And yes, the header and the footer should be the same as other pages and each page should be linked to each other.

**Comment by Baba-Yaga-1** [comment]
I am facing an error while using "git pull origin master" command. I haven't pushed any of the files yet.

![git](https://user-images.githubusercontent.com/56999749/125574182-1151ff99-55fe-4306-86c6-50e2afe825d3.JPG)

Also, I made the changes.
I set the margin and padding properly.

![set-margin](https://user-images.githubusercontent.com/56999749/125574345-1e6fb15d-4ec9-4a53-9fe0-3bdbee1972af.JPG)

I also changed the pictures in carousel. Can you check ?

https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

**Comment by QAZIMAAZARSHAD** [comment]
Your changes are not reflected in the link.

**Comment by QAZIMAAZARSHAD** [comment]
![image](https://user-images.githubusercontent.com/56196640/125578104-5949dc4d-886a-4d0f-ab11-3451af6e01ec.png)
![image](https://user-images.githubusercontent.com/56196640/125578142-9e3a438e-f317-49e9-9271-4ddba744f633.png)
![image](https://user-images.githubusercontent.com/56196640/125578169-b2eccbe6-b875-45e8-9050-4a11eccf1331.png)

**Comment by QAZIMAAZARSHAD** [comment]
@satyampgt4 please help @Baba-Yaga-1 in resolving issues.

**Comment by Baba-Yaga-1** [comment]
I am not able to understand the problem, as the changes are clearly reflected on the link when I view it. So, how can I solve the problem ?

![demo](https://user-images.githubusercontent.com/56999749/125580260-18709d12-3def-468e-9863-4b9b0abff17d.JPG)
![demo1](https://user-images.githubusercontent.com/56999749/125580275-3ce42d73-5c3c-4e41-9a10-834bc6553776.JPG)
![demo2](https://user-images.githubusercontent.com/56999749/125580283-d900a5cc-8096-4aba-bbcd-5efb3cf0f923.JPG)

**Comment by QAZIMAAZARSHAD** [comment]
@satyampgt4 look into this.

**Comment by satyampgt4** [comment]
> I am facing an error while using "git pull origin master" command. I haven't pushed any of the files yet. Can you look into it?
> 
> ![git](https://user-images.githubusercontent.com/56999749/125574182-1151ff99-55fe-4306-86c6-50e2afe825d3.JPG)
> 
> Also, I made the changes.
> I set the margin and padding properly.
> 
> ![set-margin](https://user-images.githubusercontent.com/56999749/125574345-1e6fb15d-4ec9-4a53-9fe0-3bdbee1972af.JPG)
> 
> I also changed the pictures in carousel. I have also updated the header and footer. Can you check ?
> 
> https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

is this issue get solved or not... ?

**Comment by Baba-Yaga-1** [comment]
I tried that and now its showing another error.

![commit](https://user-images.githubusercontent.com/56999749/125649923-11034e30-0b95-4c1a-b874-810e2814a639.JPG)

Also what should I do about the problem that is occurring while clicking the link ? As the changes are shown while I view the link.

**Comment by satyampgt4** [comment]
> I tried that and now its showing another error.
> 
> ![commit](https://user-images.githubusercontent.com/56999749/125649923-11034e30-0b95-4c1a-b874-810e2814a639.JPG)
> 
> Also what should I do about the problem that is occurring while clicking the link ? As the changes are shown while I view the link.

it is showing you have merge conflict if you are using vs code you can easily see the current and incoming update you have to resolve them and after all the conflict get resolved then commit it

if find any difficulty in it ping me on slack !

**Comment by Baba-Yaga-1** [comment]
Hey thanks, that issue got solved.
> 
> Also what should I do about the problem that is occurring while clicking the link ? As the changes are shown while I view the link.

But what about this ? Can you open the link and check, whether the margin and padding has been set properly or not ?

**Comment by QAZIMAAZARSHAD** [comment]
No nothing has been updated.

Everything's wrong same as before.

**Comment by satyampgt4** [comment]
> Hey thanks, that issue got solved.
> 
> > Also what should I do about the problem that is occurring while clicking the link ? As the changes are shown while I view the link.
> 
> But what about this ? Can you open the link and check, whether the margin and padding has been set properly or not ?
> 
> https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

try to use flex may be it will help you

**Comment by satyampgt4** [comment]
or use 13px in margin left and right instead of 20px

**Comment by Baba-Yaga-1** [comment]
> No nothing has been updated.
> 
> Everything's wrong same as before.

https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

**Comment by QAZIMAAZARSHAD** [comment]
Cards are now 3 in each row. But still, not properly in the center, correct the margin.

But the navbar, footer, is still wrong.
And remove that slideshow of the home page.

**Comment by Baba-Yaga-1** [comment]
> Cards are now 3 in each row. But still, not properly in the center, correct the margin.
> 
> But the navbar, footer, is still wrong.
> And remove that slideshow of the home page.

You mean the slider for the advertisement?

**Comment by QAZIMAAZARSHAD** [comment]
Yes no need for that slider, baby slider is enough.

**Comment by Baba-Yaga-1** [comment]
Okay I will update it. 

So the navbar and footer of this page should match with the index page ?

![index](https://user-images.githubusercontent.com/56999749/125752305-f3a7c17a-5f72-489b-a96b-3407cdce9f79.JPG)

**Comment by QAZIMAAZARSHAD** [comment]
Yes

**Comment by Baba-Yaga-1** [comment]
https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

**Comment by QAZIMAAZARSHAD** [comment]
Footer has been updated check.

The right margin is still a bit more.

And compress the height of the slider a bit.
Also update the images use images which also have like sale, 40% of on boys clothes, etc.

**Comment by Baba-Yaga-1** [comment]
> 
> 
> Footer has been updated check.
> 
> The right margin is still a bit more.
> 
> And compress the height of the slider a bit.
> Also update the images use images which also have like sale, 40% of on boys clothes, etc.

https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

**Comment by QAZIMAAZARSHAD** [comment]
Footer is not correct.

It should be similar to the footer as in the home page.

**Comment by Baba-Yaga-1** [comment]
> 
> 
> Footer is not correct.
> 
> It should be similar to the footer as in the home page.

https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

**Comment by QAZIMAAZARSHAD** [comment]
![image](https://user-images.githubusercontent.com/56196640/126035236-483c29ee-9a2e-4cc4-9dcf-8fd1861a952a.png)

![image](https://user-images.githubusercontent.com/56196640/126035250-7cc99b68-f175-49fc-afaa-bba3abacc393.png)

Compare.


Correct it.

**Comment by Baba-Yaga-1** [comment]
https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

I updated it.

**Comment by QAZIMAAZARSHAD** [comment]
Nope.

Not reflected in the link you shared.
![image](https://user-images.githubusercontent.com/56196640/126125148-c094cc13-2920-46e6-ac24-d06cdf3b6245.png)

**Comment by Baba-Yaga-1** [comment]
Can you check it?

https://baba-yaga-1.github.io/DevIncept/babyAndkids.html

**Comment by QAZIMAAZARSHAD** [comment]
No not correct.


Why are you struggling too much in this part, just copy the code from other pages.

**Comment by QAZIMAAZARSHAD** [comment]
Your navbar is also wrong.

Correct that as well.

**Comment by Baba-Yaga-1** [comment]
Don't you think I copied the codes ?
Let me show you the proof.
This is the home page that i am able to view after opening it from my local repo.

![homepage](https://user-images.githubusercontent.com/56999749/126285927-1f70af44-ff0f-4d1e-9bc5-c4a8c46139bb.JPG)

This is the babyandkids page,

![babyAndkidspage](https://user-images.githubusercontent.com/56999749/126286113-3824c4ce-d723-480f-a514-a73488c7a514.JPG)

These are the codes,
![cssoffooter](https://user-images.githubusercontent.com/56999749/126286196-6c1122c5-c556-4300-a687-112780093905.JPG)
![footer](https://user-images.githubusercontent.com/56999749/126286203-7b466cbc-38c3-4ca1-8d99-5e4bb24c46e7.JPG)

**Comment by QAZIMAAZARSHAD** [comment]
![image](https://user-images.githubusercontent.com/56196640/126287228-f10793ed-749b-4e64-b750-b7809b6dae64.png)
![image](https://user-images.githubusercontent.com/56196640/126287145-3f965e3f-6fcf-49d5-ae4d-c5abeab8fe4c.png)

This is the screenshot of when I open your link.

**Comment by QAZIMAAZARSHAD** [comment]
Something must be wrong.

**Comment by QAZIMAAZARSHAD** [comment]
Create a PR then we will figure out what's wrong.

**Comment by Baba-Yaga-1** [comment]
I made the PR, you can check it.
