### ISSUE TITLE
To make an attractive toggle between login & Signup pages

### ISSUE THREAD

**Issue by JMKanakadurga** [QAZIMAAZARSHAD/Apni-Dukaan#105]
## Is your feature request related to a problem? Please describe.
I can see that the login page has a very common format and yet it is not catchy .I got an idea to toggle between sign up and login section so it could be user-friendly.

## Describe the solution you'd like
I would like to create a still more attractive toggle between login and signup which could be user-friendly.

**Comment by 119kanika** [comment]
Hey @QAZIMAAZARSHAD please assign me something too. I can build and modify webpages.

**Comment by QAZIMAAZARSHAD** [comment]
> Hey @QAZIMAAZARSHAD please assign me something too. I can build and modify webpages.

@119kanika these issues are up for grab.
Select anyone,
https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%A4%A9+Up+for+Grab%22
