### ISSUE TITLE
Create a  furniture page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#11]

**Comment by RR-Sahoo** [comment]
@QAZIMAAZARSHAD Can I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DCP will start from 10th July.

**Comment by RR-Sahoo** [comment]
ok

**Comment by harshita9621** [comment]
@QAZIMAAZARSHAD Can I work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Can I work on this issue.

Already assigned.

**Comment by RR-Sahoo** [comment]
@QAZIMAAZARSHAD is there any design protocol for furniture page.

**Comment by QAZIMAAZARSHAD** [comment]
No just implement your ideas.

But header, footer, background things like this should be similar.

**Comment by RR-Sahoo** [comment]
@QAZIMAAZARSHAD  actually I have my sem exam going on so can u assign this to others who are interested

**Comment by tjanhvi** [comment]
Please assign me this issue.

**Comment by satyampgt4** [comment]
@tjanhvi any updates ...?

**Comment by tjanhvi** [comment]
> @tjanhvi any updates ...?

doing .....
I will inform you soon
