### ISSUE TITLE
Redesign the Faq page.

### ISSUE THREAD

**Issue by LeeSinYung** [QAZIMAAZARSHAD/Apni-Dukaan#113]
## Is your feature request related to a problem? Please describe.
The Faq stick the wall

## Describe the solution you'd like
Create a container for faq to avoid the problem

## Additional context
Add any other context about the feature request here.
I would like to try to modify the faq page. Can you assign this issue to me?

**Comment by LeeSinYung** [comment]
@QAZIMAAZARSHAD  I had modify the faq page. Have a look on my pull request. Thank you.

**Comment by QAZIMAAZARSHAD** [comment]
@LeeSinYung are you part of DCP?

**Comment by LeeSinYung** [comment]
I am not part of DCP.
