### ISSUE TITLE
Fix footer, navbar and heading in about us page

### ISSUE THREAD

**Issue by Ankkkitt** [QAZIMAAZARSHAD/Apni-Dukaan#115]
## Describe the bug
The heading of About Us would look good if it will be in center, have some padding from the top, and little beat changes. 
Plz, assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
Also, correct the footer and navbar.

Apply the same footer and navbar as in the home page.

**Comment by Ankkkitt** [comment]
ok. Plz, assign this issue to me.
