### ISSUE TITLE
Enhanced card border and h5 heading text decoration of cards inside Buy Now section

### ISSUE THREAD

**Issue by Surajvatsya** [QAZIMAAZARSHAD/Apni-Dukaan#119]
## Is your feature request related to a problem? Please describe.
yes, it'll enhance the user experience.

## Describe the solution you'd like
Enhanced card border and h5 heading text-decoration of cards inside Buy Now section
## Additional context
![image](https://user-images.githubusercontent.com/68156079/125829400-e7603531-74f5-4621-ae76-e9bf7d298612.png)

**Comment by QAZIMAAZARSHAD** [comment]
Not needed.

Look for some other issues.
