### ISSUE TITLE
Apply creative hover effect on navbar

### ISSUE THREAD

**Issue by Surajvatsya** [QAZIMAAZARSHAD/Apni-Dukaan#125]

**Comment by QAZIMAAZARSHAD** [comment]
@Surajvatsya update the navbar on every single page.

And apply this effect.

**Comment by mayuribotre15** [comment]
Is this issue still open?
I want to apply a creative hover effect on the navbar.

**Comment by mayuribotre15** [comment]
I am working on your task. I will get back to you as soon as task completed.

**Comment by RituSingh2002** [comment]
@QAZIMAAZARSHAD I would like to work on than issue

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I would like to work on than issue

Do it for all the pages.

**Comment by anupammaurya6767** [comment]
@QAZIMAAZARSHAD Only color change or any size change also on hovering?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Only color change or any size change also on hovering?

Yes, color change, size change, hover effect.
Everything you can do to enhance the look.
