### ISSUE TITLE
Remove about us section from home page and create a separate about us page 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#13]

**Comment by K-jais** [comment]
Please assign this issue to me. I will remove the about us page from the home and make a separate page for it.

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DevIncept will commence from 10th July.

**Comment by K-jais** [comment]
Ok sir.

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD sir I would like to work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign this issue to me. I will remove the about us page from the home and make a separate page for it.

I have assigned you other issues so I assigned this to @techabhi08.

**Comment by techabhi08** [comment]
Sir I have made the changes should I submit the PR?

**Comment by QAZIMAAZARSHAD** [comment]
> Sir I have made the changes should I submit the PR?

Tomorrow

**Comment by techabhi08** [comment]
Okay sir

**Comment by techabhi08** [comment]
Sir this issue will be considered for DevIncept right? I am just asking because you removed the label.

**Comment by QAZIMAAZARSHAD** [comment]
> Sir this issue will be considered for DevIncept right? I am just asking because you removed the label.

I was just adding new ones.

**Comment by techabhi08** [comment]
Okay sir.
