### ISSUE TITLE
Make individual CSS file for each html file.

### ISSUE THREAD

**Issue by tjanhvi** [QAZIMAAZARSHAD/Apni-Dukaan#132]
Please assign me this issue

**Comment by tjanhvi** [comment]
And also it creating major issue in website.

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead.

Make an individual CSS file for each page.
Add all the CSS files to the CSS folder.
Also, add all the HTML files to the HTML folder except the index.html.

**Comment by tjanhvi** [comment]
> Go ahead.
> 
> Make an individual CSS file for each page.
> Add all the CSS files to the CSS folder.
> Also, add all the HTML files to the HTML folder except the index.html.

okay :)
