### ISSUE TITLE
Check links in the navbar of all pages

### ISSUE THREAD

**Issue by Surajvatsya** [QAZIMAAZARSHAD/Apni-Dukaan#133]

**Comment by satyampgt4** [comment]
@Surajvatsya  any update...?

**Comment by QAZIMAAZARSHAD** [comment]
@Surajvatsya you have to link all pages with each other.

**Comment by QAZIMAAZARSHAD** [comment]
@Surajvatsya another similar issue is open if you like to resolve it ping me there.
