### ISSUE TITLE
Correct navbar in all pages and link every page with each other

### ISSUE THREAD

**Issue by tjanhvi** [QAZIMAAZARSHAD/Apni-Dukaan#134]
It will look decent . Some pages have  nave bar in dark blue color and too thick so i want to set it all in proper way..
Please assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Also, update all the footers.

Navbar and footer on the homepage are correct.

**Comment by Kulshre142** [comment]
@QAZIMAAZARSHAD  Can I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
@Kulshre142 any updates?
