### ISSUE TITLE
Better UI for Login Page

### ISSUE THREAD

**Issue by Surajvatsya** [QAZIMAAZARSHAD/Apni-Dukaan#135]
## Describe the bug
Awful UI must be changed on the login page.
## To Reproduce
1. Change heading position.
2. change the logo background, it should be in the left corner.
3. Enhance input field.
4. Enhance buttons position.

## Expected behavior
Better from the previous version.

## Environment (please complete the following information):

 - Browser:

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open.

Before opening any issue make sure that no other similar issue is open.
