### ISSUE TITLE
Incoherent search bar and search button on offer page.

### ISSUE THREAD

**Issue by Surajvatsya** [QAZIMAAZARSHAD/Apni-Dukaan#136]
## Describe the bug
Incoherent search bar and search button on offer page.

## To Reproduce
1. Width of the search box must be equal to the width of the search button.

## Expected behavior
Width of both search box and search button should be same.

raceback).

## Environment (please complete the following information):

 - Browser:

## Additional context
![image](https://user-images.githubusercontent.com/68156079/126045224-c121ce0f-0c5d-4a0f-a1bd-9892941823ac.png)

**Comment by QAZIMAAZARSHAD** [comment]
This issue will be dealt with in another already opened issue.
