### ISSUE TITLE
Create a career page

### ISSUE THREAD

**Issue by Ayonijakaushik19** [QAZIMAAZARSHAD/Apni-Dukaan#137]
It should follow the theme of the website.

Add the same navbar and footer as on the website.

**Comment by QAZIMAAZARSHAD** [comment]
Yes, that's because the career page does not exist.

**Comment by QAZIMAAZARSHAD** [comment]
Would you like to design a career page for this website?

Refer to some other company websites to get an idea of the career page.

**Comment by Ayonijakaushik19** [comment]
Hi @QAZIMAAZARSHAD 
Sure, I would love to design a career page for this website. Please assign this to me.
Thanks

**Comment by QAZIMAAZARSHAD** [comment]
> Hi @QAZIMAAZARSHAD
> Sure, I would love to design a career page for this website. Please assign this to me.
> Thanks

Are you a part of DCP?

**Comment by satyampgt4** [comment]
@Ayonijakaushik19   any update...?

**Comment by K-jais** [comment]
Assign this issue to me 
@QAZIMAAZARSHAD
