### ISSUE TITLE
Create a "Apni Dukaan Cares" page

### ISSUE THREAD

**Issue by Ayonijakaushik19** [QAZIMAAZARSHAD/Apni-Dukaan#139]
It should include social missions, campaigns, charity actions taken by the company Apni Dukaan for society.

Refer to other websites to get an idea.

**Comment by Ayonijakaushik19** [comment]
Hi, @QAZIMAAZARSHAD ,I like to design the cares page for Apni dukaan . Please assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
> Hi, @QAZIMAAZARSHAD ,I like to design the cares page for Apni dukaan . Please assign this to me.

I assigned you career page issue.
Once you are done with that I will assign you.

**Comment by pushpakumari5117** [comment]
Hello @QAZIMAAZARSHAD, I would love to design this page. Can you please assign this issue to me?

**Comment by satyampgt4** [comment]
@pushpakumari5117 any updates

**Comment by pushpakumari5117** [comment]
> @pushpakumari5117 any updates

@satyampgt4 I am working on it.
