### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#14]

**Comment by harshithatnbr** [comment]
I would like to work on this issue. Please assign it to me under DCP 2021. Thankyou.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue. Please assign it to me under DCP 2021. Thankyou.

@harshithatnbr DCP will commence from 10th July, I will assign you then only otherwise you won't get any points for your work.

**Comment by harshithatnbr** [comment]
Ok thankyou.

**Comment by harshithatnbr** [comment]
Thanks for assigning the issue. I have a doubt. If I click login button there is already a sign-up page on the website. Should I redesign it or create an other login page?
If so what details should be included in login page? Please let me know.
Thankyou.

**Comment by QAZIMAAZARSHAD** [comment]
> Thanks for assigning the issue. I have a doubt. If I click login button there is already a sign-up page on the website. Should I redesign it or create an other login page?
> If so what details should be included in login page? Please let me know.
> Thankyou.

@harshithatnbr login page and signup page are different.

The login page will include only email input, password input, and a login button.

**Comment by satyampgt4** [comment]
@harshithatnbr any update .... ?

**Comment by Sia0** [comment]
Hi @QAZIMAAZARSHAD  May I know can I work on this after harshithatnbr done?

**Comment by harshithatnbr** [comment]
@Sia0 if you find any issues after I submit my work . You can raise an issue and work on it.

**Comment by Sia0** [comment]
ohhh ok noted.

**Comment by harshithatnbr** [comment]
![image](https://user-images.githubusercontent.com/56475512/126371380-9f7d7f74-046e-44d6-b366-f0169afc66fb.png)
@QAZIMAAZARSHAD 
This is the present index page of website.  Should I keep the login page when the user clicks **get started** button? Or should I keep Login page as index page of website ?

**Comment by harshithatnbr** [comment]
https://Apni-Dukaan.harshithatnbr.repl.co
@QAZIMAAZARSHAD  I have designed login page as index page and sharing the website. Please tell me the changes I have to do before I make pull request.

**Comment by QAZIMAAZARSHAD** [comment]
No, when the user clicks on Get started then the user should be redirected to login page.

Don't change the index page.
