### ISSUE TITLE
Design Shipping Page.

### ISSUE THREAD

**Issue by Ayonijakaushik19** [QAZIMAAZARSHAD/Apni-Dukaan#141]
## Is your feature request related to a problem? Please describe.
I got to know that the Shipping page does not exist for this website. because when I was clicking on the page it is redirecting me to the Home/Same page.
## Describe the solution you'd like
I would design a Shipping page for this website.

**Comment by K-jais** [comment]
Please assign this issue to me. I will design this page that goes well with the theme of the website.

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign this issue to me. I will design this page that goes well with the theme of the website.

Other issues are also assigned to you first resolve them.

**Comment by K-jais** [comment]
Now assign this issue to me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> Now assign this issue to me @QAZIMAAZARSHAD

Resolve other issues first. Taking many issues at a time will not help.

**Comment by K-jais** [comment]
Now assign this issue to me @QAZIMAAZARSHAD
