### ISSUE TITLE
Grammatical error in second last question of FAQ page.

### ISSUE THREAD

**Issue by Ayonijakaushik19** [QAZIMAAZARSHAD/Apni-Dukaan#142]
## Describe the bug
There is a grammatical error in  the answer of the second last question of FAQ..

## To Reproduce
1. Go to FAQ page.
2. Scroll down to the second last question.
3. Click on that.

## Environment (please complete the following information):
 - Browser:

**Comment by Ayonijakaushik19** [comment]
![image](https://user-images.githubusercontent.com/84201769/126056470-ecac76b3-f2d0-469e-ae04-119d7082d13d.png)

**Comment by Ayonijakaushik19** [comment]
Hi  @QAZIMAAZARSHAD ,please assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
Yes go ahead.


Also, rename Flipkart to Apni Dukaan.

**Comment by QAZIMAAZARSHAD** [comment]
@Ayonijakaushik19 are you part of DCP?

**Comment by Ayonijakaushik19** [comment]
hi @QAZIMAAZARSHAD , i have raise a PR  for this issue. Kindly review.
