### ISSUE TITLE
I have designed some of the creative logos for this website

### ISSUE THREAD

**Issue by Ayonijakaushik19** [QAZIMAAZARSHAD/Apni-Dukaan#144]
## Describe the solution you'd like
I have designed few unique and creative logos which serves the purpose of this website.

## 1.
![image](https://user-images.githubusercontent.com/84201769/126057557-f21e883e-34e2-4fa4-9082-10f97e9ca88c.png)

##2.
![image](https://user-images.githubusercontent.com/84201769/126057585-3b2fbe42-208b-464c-927b-bdea5ba5626e.png)

##3.
![image](https://user-images.githubusercontent.com/84201769/126057606-549d9f45-34d7-4633-80fb-ddc250216f2a.png)

##4.
![image](https://user-images.githubusercontent.com/84201769/126057624-e9954902-74d6-4306-a0bd-7128212c0bc4.png)

##5.
![image](https://user-images.githubusercontent.com/84201769/126057637-6bcafa1d-64b6-4f35-90c8-b6595bd56a99.png)

**Comment by Ayonijakaushik19** [comment]
Hi @QAZIMAAZARSHAD , please suggest me which looks fine to you ?

**Comment by QAZIMAAZARSHAD** [comment]
The Blue one matches the theme a bit.

Except for the last one, all look good.

**Comment by QAZIMAAZARSHAD** [comment]
@Ayonijakaushik19 this issue is already open.

Before opening any issue make sure that no other similar issue is open.

**Comment by QAZIMAAZARSHAD** [comment]
@Ayonijakaushik19 you can make PR for https://github.com/QAZIMAAZARSHAD/Apni-Dukaan/issues/2.

Add logo 1 and 4 only in the Logo folder.

**Comment by Ayonijakaushik19** [comment]
Hi @QAZIMAAZARSHAD ,i have made a PR for #2.Please review.
