### ISSUE TITLE
Design the search feature for this website.

### ISSUE THREAD

**Issue by Ayonijakaushik19** [QAZIMAAZARSHAD/Apni-Dukaan#147]
## Is your feature request related to a problem? Please describe.
Whatever is given in search option , is redirecting me to the home page instead of the items page.

## Describe the solution you'd like
There should be different pages according to search lists.

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open, before opening any issues make sure that no other similar issue is open.
