### ISSUE TITLE
Redesign the sign-up page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#15]

**Comment by Swastik1710** [comment]
Hey , I can create a fully responsive signup page.Please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DevIncept will commence from 10th July.

**Comment by harshita9621** [comment]
@QAZIMAAZARSHAD Can I work on this issue under DCP'21.

**Comment by QAZIMAAZARSHAD** [comment]
> Hey , I can create a fully responsive signup page.Please assign this issue to me.

I have assigned you another issue so I assigned this one to @harshita9621.

**Comment by Swastik1710** [comment]
> > Hey , I can create a fully responsive signup page.Please assign this issue to me.
> 
> I have assigned you another issue so I assigned this one to @harshita9621.

No worries.

**Comment by satyampgt4** [comment]
@harshita9621  any update .... ?

**Comment by Swastik1710** [comment]
Can I work on this @QAZIMAAZARSHAD?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this @QAZIMAAZARSHAD?

Let's wait and see if @harshita9621 is working on it or not.

**Comment by Swastik1710** [comment]
Okay.
If no one else is working, do let me know.

**Comment by harshita9621** [comment]
@QAZIMAAZARSHAD Working on it.

**Comment by rompyroshni31** [comment]
@QAZIMAAZARSHAD Hey! Assign me something too! I can also design web pages.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Hey! Assign me something too! I can also design web pages.

@rompyroshni31 select any one of these.

https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%A4%A9+Up+for+Grab%22

**Comment by satyampgt4** [comment]
@harshita9621 are you facing any difficulties while solving this issue...?

**Comment by Swastik1710** [comment]
Hey, can i work on this?

**Comment by Swastik1710** [comment]
![ezgif com-gif-maker(5)](https://user-images.githubusercontent.com/71871571/128065065-5df9171b-414b-4361-8d37-eebfdd05feb2.gif)

@QAZIMAAZARSHAD , please have a look.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD , please have a look.

Looks great you can make PR. Check validation as well.
Username must accept only alphanumeric characters.
Password must have at least one uppercase letter, one number, one special character, and minimum length must be 8 and max 16.

Also, check the responsiveness.
