### ISSUE TITLE
Add "Our Partners" link in the footer

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#156]
Add it in the "Get to know us" section.
Link it with the partners page.

Update footers of all the pages.

**Comment by dineshkumar12004** [comment]
hey can i work on this issue @QAZIMAAZARSHAD

**Comment by satyampgt4** [comment]
@dineshkumar12004  any update...?

**Comment by dineshkumar12004** [comment]
was busy with some other stuff sorry you can take it @satyampgt4

**Comment by mayank-wadhwa-git** [comment]
I would like to work on this issue @QAZIMAAZARSHAD
