### ISSUE TITLE
Add a custom scroll bar in all pages of website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#16]

**Comment by Swastik1710** [comment]
Hey, I've made such custom scroll bar for my website earlier. Would love to work on this. Please assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
I will start assigning issues from 10th July when DCP will start.

**Comment by Swastik1710** [comment]
Sure @QAZIMAAZARSHAD .
Just commenting as issues are given on fcfs basis.

**Comment by QAZIMAAZARSHAD** [comment]
> Sure @QAZIMAAZARSHAD .
> Just commenting as issues are given on fcfs basis.

No, I don't think that would be the case because organizers will release some guidelines and contributed will have to select projects.
Also, I won't be assigning all the issues to only a few participants if others are also in line.

**Comment by Swastik1710** [comment]
Hey @QAZIMAAZARSHAD , can you please suggest the color for the thumb and for the track ?

**Comment by QAZIMAAZARSHAD** [comment]
Dark and light blue like the theme of the website.

**Comment by Swastik1710** [comment]
Is this one fine ?
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/71871571/125091752-518d8700-e0ee-11eb-90f9-874373e0e3eb.gif)

**Comment by QAZIMAAZARSHAD** [comment]
Make blue colour more dark like navbar.

**Comment by Swastik1710** [comment]
![Screenshot 2021-07-09 195700](https://user-images.githubusercontent.com/71871571/125093423-e80e7800-e0ef-11eb-8a5d-f2e911095c0c.jpg)
 
Like this ?

**Comment by QAZIMAAZARSHAD** [comment]
Ya fine.

Make PR after 10th.

**Comment by satyampgt4** [comment]
@QAZIMAAZARSHAD is this issue still require or should i close it
