### ISSUE TITLE
Change the content of font size  of the footer and adjust it in proper manner.

### ISSUE THREAD

**Issue by tjanhvi** [QAZIMAAZARSHAD/Apni-Dukaan#162]
Please assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Will assign you.

First, resolve the other issues that are assigned to you.

**Comment by tjanhvi** [comment]
> Will assign you.
> 
> First, resolve the other issues that are assigned to you.

okay sure :)

**Comment by bindalsarthak03** [comment]
assign me ...i can do this

**Comment by QAZIMAAZARSHAD** [comment]
> assign me ... I can do this

@bindalsarthak03 two similar issues are already open.

You can try these up for grab issues.
https://github.com/QAZIMAAZARSHAD/Apni-Dukaan/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%A4%A9+Up+for+Grab%22
