### ISSUE TITLE
Add a scroll to top button in footer

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#17]

**Comment by K-jais** [comment]
Please assign this issue to me. I have added this feature in my projects a lot.

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DevIncept will commence from 10th July.

**Comment by K-jais** [comment]
Ok sir.

**Comment by Tulsi25** [comment]
Hello , I am Tulsi . I would like to work on this issue under DevIncept program. Please assign this issue to me. 
I have added a sample of my previous work for the reference . @QAZIMAAZARSHAD 
![scroll bottom to up](https://user-images.githubusercontent.com/71713383/124652137-5f0dfb80-deb9-11eb-949d-744f9095e5b1.png)

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DevIncept will commence from 10th July.

**Comment by Tulsi25** [comment]
ok sir
