### ISSUE TITLE
Remove horizontal scroll bar from website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#18]

**Comment by Yannick-N** [comment]
I've just finish to remove the horizontal scroll bar from website in file index.html !

**Comment by QAZIMAAZARSHAD** [comment]
@Yannick-N remove it from every page.

**Comment by QAZIMAAZARSHAD** [comment]
@Yannick-N are you a part of DevIncept event?

**Comment by Yannick-N** [comment]
No I'm not, but It's done I fix this on my branch.

**Comment by QAZIMAAZARSHAD** [comment]
sure

**Comment by Yannick-N** [comment]
Sorry It's my first time doing a pull request, I can't find my branch don't you know why ?

**Comment by Yannick-N** [comment]
I have this when I want to push : 
`ERROR: Permission to QAZIMAAZARSHAD/Apni-Dukaan.git denied to Yannick-N.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by QAZIMAAZARSHAD** [comment]
You have to first push changes in your forked repository then make PR to my repository.

**Comment by Yannick-N** [comment]
I've done the pull request !

**Comment by Yannick-N** [comment]
Did you received the PR ?

**Comment by QAZIMAAZARSHAD** [comment]
Yes, will review soon.
