### ISSUE TITLE
Add a creative pre-loader in website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#19]
Use the logo of the website and apply some creative effects

**Comment by Kjp04** [comment]
Can I work on this issue @QAZIMAAZARSHAD

**Comment by navyasrisangem** [comment]
Please assign this issue to me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign this issue to me @QAZIMAAZARSHAD

This is already assigned.
Look for up for grab level in other issues. I will assign you that issues.

**Comment by QAZIMAAZARSHAD** [comment]
@Kjp04 any updates?

**Comment by Kjp04** [comment]
I made few changes please let me know are the conflicts resolved?

**Comment by QAZIMAAZARSHAD** [comment]
> I made few changes please let me know are the conflicts resolved?

No.

Your repo is 150 commits behind. Fetch upstream.


And share a link of your website so I can review your changes.

**Comment by Kjp04** [comment]
I will make the required changes
Thank you!
