### ISSUE TITLE
Design a new creative logo for website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#2]
The logo should follow the theme of the website.
Don't change the website name.
You can add a new catchy slogan or tagline.

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD sir please assign this issue to me. I will try to make a suitable and attractive logo.

**Comment by techabhi08** [comment]
![Screenshot (478)](https://user-images.githubusercontent.com/75834097/125164183-95e05c00-e1ae-11eb-8e2b-65e84bc82f43.png)

Sir can I go with this design or design something else?

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

You can try more designs.
Try some desi tagline which matches with the name "Apni Dukaan".

**Comment by techabhi08** [comment]
okay sir.

**Comment by QAZIMAAZARSHAD** [comment]
Also, it has website signature remove it in the next logos.

**Comment by techabhi08** [comment]
yes sir actually it was a screen shot. When I will download it will be removed. I tried that.

**Comment by QAZIMAAZARSHAD** [comment]
Fine

**Comment by navyasrisangem** [comment]
Please assign this issue to me sir @QAZIMAAZARSHAD

**Comment by techabhi08** [comment]
![imageonline-co-resizedimage (1)](https://user-images.githubusercontent.com/75834097/125167090-69cbd780-e1bc-11eb-85d9-eb1dbdee8ed1.png)

**Comment by QAZIMAAZARSHAD** [comment]
@techabhi08 looks cool.

But replace the dollar sign with a rupee.

**Comment by techabhi08** [comment]
Ok sir. Then should I create a pull request?

**Comment by QAZIMAAZARSHAD** [comment]
> Ok sir. Then should I create a pull request?

Create a folder named logo in the images folder and add both your files there.

**Comment by techabhi08** [comment]
Okay sir

**Comment by QAZIMAAZARSHAD** [comment]
@satyampgt4 let's keep this issue open.

So other participants can also share their ideas and we will use the best logo.

**Comment by 889-dj** [comment]
@QAZIMAAZARSHAD  can I work on this

**Comment by 889-dj** [comment]
@QAZIMAAZARSHAD  can I work on this under DCP 21

**Comment by 889-dj** [comment]
889-dj:newLogo

@QAZIMAAZARSHAD  I have made a PR

**Comment by 889-dj** [comment]
![3](https://user-images.githubusercontent.com/73821023/125391290-d6fc8a00-e3c1-11eb-8e66-5fdbfa84aa60.jpg)

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I have uploaded the images once again plz check it once

Make PR again.

**Comment by anupammaurya6767** [comment]
![Screenshot 2022-04-17 123119](https://user-images.githubusercontent.com/96181413/163704344-93f4b11d-b4ff-4e73-bd43-363344e010aa.png)


@QAZIMAAZARSHAD how's this one?

**Comment by QAZIMAAZARSHAD** [comment]
Nice,

Update the tagline "Online Solution" with something more Indian just like the name 'Apni Dukaan'.

**Comment by anupammaurya6767** [comment]
![rgs](https://user-images.githubusercontent.com/96181413/163706155-ba34a458-8228-419b-9116-595bcbe19a66.png)


@QAZIMAAZARSHAD old tagline cant find anything else 😅

**Comment by QAZIMAAZARSHAD** [comment]
Fine,


Add the image in the logo folder.
Images -> Logo



You can also update the logo everywhere on the website.

**Comment by neeraj542** [comment]
**want to work in this issue**

**Comment by neeraj542** [comment]
![LOGO-APNIDUKAN](https://user-images.githubusercontent.com/114648043/193740304-28ebb9ac-1fd2-4bb0-b286-98ff3a10cc85.png)

**Comment by neeraj542** [comment]
should I upload it on website

**Comment by QAZIMAAZARSHAD** [comment]
> should I upload it on website

No, It doesn't look great.

Just add your logo image in the logo's folder.

**Comment by neeraj542** [comment]
Logo uploadation is done in that particular folder

**Comment by QAZIMAAZARSHAD** [comment]
> Logo uploadation is done in that particular folder

Raise PR then.

**Comment by 889-dj** [comment]
hello @QAZIMAAZARSHAD sir I also wanted to work on this

**Comment by 889-dj** [comment]
![1](https://user-images.githubusercontent.com/73821023/194504584-8ce46656-2c96-4e51-bbe1-9cf7c9e4c7e5.png)
![2](https://user-images.githubusercontent.com/73821023/194504617-d8fe5f7a-7034-470c-a1de-453347
![3](https://user-images.githubusercontent.com/73821023/194504643-9324a80b-63f8-42e2-8c25-3fab49c31508.png)
c86737.png)

hope these luks gud :)

**Comment by 889-dj** [comment]
@QAZIMAAZARSHAD  can I add the images in the logo folder and make a pr ?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD can I add the images in the logo folder and make a pr ?

@889-dj 
![image](https://user-images.githubusercontent.com/56196640/194705798-736147af-3b34-443e-81bb-edc40b4c7b29.png)


This looks good. 
You can update logo everywhere in the website.

**Comment by 889-dj** [comment]
> > @QAZIMAAZARSHAD can I add the images in the logo folder and make a pr ?
> 
> @889-dj ![image](https://user-images.githubusercontent.com/56196640/194705798-736147af-3b34-443e-81bb-edc40b4c7b29.png)
> 
> This looks good. You can update logo everywhere in the website.

hello @QAZIMAAZARSHAD just a lil query as there are so many files to be edited its becoming a lil clumsy for me though i have make changes to 4 files could u plz tell me if i should squash these prs or simply open different pull request

**Comment by QAZIMAAZARSHAD** [comment]
I suggest make a fresh PR where all the pages are updated.

**Comment by 889-dj** [comment]
> I suggest make a fresh PR where all the pages are updated.

can u plz guide me how to do that as i have searched for it that's why i raised this query or are u simply suggesting me to squash my commits

**Comment by 889-dj** [comment]
> > I suggest make a fresh PR where all the pages are updated.
> 
> can u plz guide me how to do that as i have searched for it that's why i raised this query or are u simply suggesting me to squash my commits
as i searched for it and the first result from stackoverflow says to directly commit the master and as part of internal branching all the prs can be there at once

**Comment by QAZIMAAZARSHAD** [comment]
Can't understand the problem you are facing.

Just make a new branch, and add the logo in the logo folder.
Update the src on every page where the logo is used.
Then commit your changes and make PR.

**Comment by 889-dj** [comment]
> Can't understand the problem you are facing.
> 
> Just make a new branch, and add the logo in the logo folder. Update the src on every page where the logo is used. Then commit your changes and make PR.

Sure got it I will make the changes asap
