### ISSUE TITLE
Design a FAQ page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#22]

**Comment by Swastik1710** [comment]
Hey, I can design a FAQ page. So please assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
Wiat till 10th July

**Comment by harshita9621** [comment]
@QAZIMAAZARSHAD Can I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Can I work on this issue?

Look for some other issues. Will assign you if this remains unresolved for a few days.

**Comment by Swastik1710** [comment]
Hey @QAZIMAAZARSHAD , thanks for assigning this issue to me.
Can you please suggest some questions for the faq page.

**Comment by QAZIMAAZARSHAD** [comment]
I suggest referring to the FAQ pages of some e-commerce websites.

You can include questions like 

What is the return policy?
How long it takes for the shipment to arrive?
Is service available in my country?
etc.

**Comment by Swastik1710** [comment]
Hey @QAZIMAAZARSHAD , please have a look !

![ezgif com-gif-maker](https://user-images.githubusercontent.com/71871571/125086178-fd33d880-e0e8-11eb-81e5-7c286d7a8849.gif)

**Comment by QAZIMAAZARSHAD** [comment]
Looks nice.

check responsiveness as well.

Make PR after 10th.

**Comment by harshita9621** [comment]
@QAZIMAAZARSHAD Can I work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Can I work on this issue.

This issue has already been resolved.
