### ISSUE TITLE
Make navbar fixed

### ISSUE THREAD

**Issue by rohit306-bit** [QAZIMAAZARSHAD/Apni-Dukaan#220]
## Is your feature request related to a problem? Please describe.
when we make static header section which is best for navigation perspective because if we go to the bottom of page then we doesn't scroll up again because static header section stick on top so we easily navigate on the other pages and other features.

## Additional context
Add any other context about the feature request here.

**Comment by RituSingh2002** [comment]
@QAZIMAAZARSHAD   I would like to work on than issue
