### ISSUE TITLE
Update screenshots in the readme

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#224]

**Comment by trantran199** [comment]
is it still open?

**Comment by Shravanikale** [comment]
hey @QAZIMAAZARSHAD i want to work on this issue can you please assign it to me!!here is the sample for it(Home-page)!-
![Uploading screencapture-qazimaazarshad-github-io-Apni-Dukaan-home-html-2022-10-03-15_01_45.png…]()

**Comment by ysh-01** [comment]
Hi. I can update the screenshots in read-me file. Can you please assign this issue to me?

**Comment by QAZIMAAZARSHAD** [comment]
Add screenshots of every page.

**Comment by ysh-01** [comment]
Sure!
