### ISSUE TITLE
Design a landing page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#23]
It should redirect to the login page

**Comment by RR-Sahoo** [comment]
Hey can I work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Sure.

But I will assign you this issue when DCP will start from 10th July.

**Comment by RR-Sahoo** [comment]
ok

**Comment by satyampgt4** [comment]
@RR-Sahoo any update ...?

**Comment by RR-Sahoo** [comment]
@QAZIMAAZARSHAD  actually I have my sem exam going on so can u assign this to others who are interested

**Comment by Shivani13121007** [comment]
can I work on this?

**Comment by Shivani13121007** [comment]
Please review the landing page as there is not much more so this is what I made.
If you want to suggest anything then you can else I make PR if You like my work.

Well I will make mobile filtration section as well but its not in your page therefore I didn't added it

![Screenshot (145)](https://user-images.githubusercontent.com/68291301/125829233-1a5a27b1-50c4-4c0f-b83f-98b4f8504729.png)
![Screenshot (147)](https://user-images.githubusercontent.com/68291301/125829302-cde30fe5-71cc-441e-b260-654895d9c037.png)

**Comment by Shivani13121007** [comment]
I tried to use the same images that was in your home page but other images can be used in place of that.
Here is the footer Section
![Screenshot (146)](https://user-images.githubusercontent.com/68291301/125829899-a0690567-9ae5-4219-962e-b65e78d750dc.png)

**Comment by QAZIMAAZARSHAD** [comment]
@Shivani13121007 your design looks nice but this is the home page.

By landing page, I meant something like  this
![image](https://user-images.githubusercontent.com/56196640/125830668-9d7f2ef3-ed97-477f-877d-06edaea227c7.png)

After clicking get started user will be redirected to the login/signup page
After signing in user will be redirected to the home page

**Comment by Shivani13121007** [comment]
Ohhh okk i got your point...
I'll complete it by today

**Comment by Shivani13121007** [comment]
How can i get the updated code of index.html file?
As I did git fetch upstream But it shows the same navbar as that was  earlier

**Comment by QAZIMAAZARSHAD** [comment]
![image](https://user-images.githubusercontent.com/56196640/126069980-d87b0bf9-71d2-4a99-ae0b-b5c1b9dc6e46.png)

See it is saying this branch is 51 commits behind my branch.
You will see the fetch upstream on the right side.
Click on it.

Then clone the updated repo.

**Comment by Shivani13121007** [comment]
Is it fine?
![Screenshot (157)](https://user-images.githubusercontent.com/68291301/126073011-94e99786-1579-4fea-99d8-570cfeffc392.png)

**Comment by QAZIMAAZARSHAD** [comment]
Looks nice.

Make sure this page should be index.html.
Rename index.html to home.html.
Redirect the Get Started button to the login page.
Change the location of links in all pages, since index.html will be home.html.

**Comment by Shivani13121007** [comment]
so when should I display index.html file?
I mean when user clicks on home.html file he will be redirected to home page 
so should I Redirect user on index.html page when he clicks on logo?

**Comment by Shivani13121007** [comment]
I'm done with these 4 instructions:

Make sure this page should be index.html.
Rename index.html to home.html.
Redirect the Get Started button to the login page.
Change the location of links in all pages, since index.html will be home.html.

**Comment by QAZIMAAZARSHAD** [comment]
Fine make PR.

Also, share the link to your website so I can review your changes.

**Comment by Shivani13121007** [comment]
https://elated-wozniak-048845.netlify.app/
