### ISSUE TITLE
Link all the pages to footer in all pages

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#233]
For Example - The partner Store page should be linked to "Become our partner" in the footer.

**Comment by AmjadNoor** [comment]
Can you assign it to me?

**Comment by AmjadNoor** [comment]
> For Example - The partner Store page should be linked to "Become our partner" in the footer.

- For **Become our partners** we should have separate page I think so. Like a form page where the company will fill his information to collaborate with _Apnidukaan.com_.

- Also many pages were not created for ex:- for reporting an issue, cancellation and return etc.

# What should I do then can you guide me further?

**Comment by QAZIMAAZARSHAD** [comment]
Link all the pages that are already available. 


As for those pages that are not yet created. 
You can go ahead and open issues to create those pages. 


You can also try to create those pages. 


And about the submission form idea for become our partners page. 
You can go ahead and try to add more features and your ideas to improve the partners page. 


But as of now just linking the partners page to the footer will be fine.
