### ISSUE TITLE
Create a "My Cart" page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#24]
When the user clicks on add to cart, it should add that item to my cart.

**Comment by K-jais** [comment]
Please assign this issue to me. I will create this my cart page and can also add the functionality of add to cart in this website as I have previously added this feature in one of my projects.

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DevIncept will commence from 10th July.

**Comment by K-jais** [comment]
Ok sir.

**Comment by satyampgt4** [comment]
@K-jais any update on the issue ...?

**Comment by K-jais** [comment]
I will make the PR of this issue in 2 days
