### ISSUE TITLE
Make the navbar sticky

### ISSUE THREAD

**Issue by sanjana317** [QAZIMAAZARSHAD/Apni-Dukaan#248]
The navbar can be made sticky to enhance the design. It'll make it easier for users because they don't have to scroll every time.
Could you assign me this under hacktoberfest2022?

**Comment by QAZIMAAZARSHAD** [comment]
Do it for all the pages on the website.

**Comment by shrutimeg** [comment]
I want to solve this issue please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
> I want to solve this issue please assign this issue to me.

@sanjana317 is working on this issue.

**Comment by MohamedMafaz** [comment]
Is anyone working on this issue . If not you can assign me this issue
