### ISSUE TITLE
Improve the payments page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#25]

**Comment by Rishita11** [comment]
Please assign me this issue under DevIncept. I have already worked on a payment gateway for a website.

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DCP will start from 10th July.

**Comment by Rishita11** [comment]
Thank you

**Comment by DarshGupta1910** [comment]
@Rishita11 any update?

**Comment by satyampgt4** [comment]
@Rishita11 are you working on it ....?

**Comment by Rishita11** [comment]
I have completed this. But I am facing a problem in creating a pull request. Kindly help me with the same.

**Comment by DarshGupta1910** [comment]
@Rishita11 please share a screenshot of the issue you are facing

**Comment by Rishita11** [comment]
@DarshGupta1910  Thank you, but I have resolved the issue now.

**Comment by satyampgt4** [comment]
@QAZIMAAZARSHAD  is this solved or in process ....?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD is this solved or in process ....?

Open
