### ISSUE TITLE
Distorted Page after clicking BUY

### ISSUE THREAD

**Issue by c99SRS** [QAZIMAAZARSHAD/Apni-Dukaan#252]
## Describe the bug

When you're clicking buy on the bookstore, it is redirecting to a distorted page. 
## To Reproduce
1.  Go to BookStore
2.  Then click on any card to **BUY**
3. After clicking buy, some dummy page is coming
4. You can see the  distorted orientation

## Expected behavior
Alignment and page orientation are totally different from the parent page. It should be consistent

## Logs
Couldn't upload a screenshot directly. Mentioning image links
https://ibb.co/W6wmdxP
https://ibb.co/BBtdLLR
https://ibb.co/dG493yY

## Environment (please complete the following information):
 - OS: 
 - Browser: Chrome

## Additional context
Please assign this one to me

**Comment by c99SRS** [comment]
HI @QAZIMAAZARSHAD please assign this issue to me under hacktoberfest tag.  Please let me know if can't reproduce this one. Happy to make changes

**Comment by QAZIMAAZARSHAD** [comment]
@c99SRS #250 this issue is already open and you are working on it.
Replace the dummy page with that error page when you are done.

If you want you can create a new buy page or products page when the user clicks on buy.
