### ISSUE TITLE
Add a drop down list in navbar for more categories and remove the category navbar

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#26]
Categories like Mobiles, clothes, kids.

It should redirect to respective pages.

**Comment by priyanshk20** [comment]
I would like to do this

**Comment by sujay2306** [comment]
CAN I GET THIS

**Comment by QAZIMAAZARSHAD** [comment]
> CAN I GET THIS

Already assigned look for some other issues.

**Comment by satyampgt4** [comment]
@priyanshk20 any update.....?

**Comment by priyanshk20** [comment]
I m sorry, was stuck in some work.. will get it done by tomorrow
