### ISSUE TITLE
Make website completely responsive in mobile view

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#27]

**Comment by K-jais** [comment]
Please assign this issue to me. I have done these things quite a few times in my projects and can do this very efficiently.

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DevIncept will commence from 10th July.

**Comment by K-jais** [comment]
Ok sir.

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD sir can you please assign this issue to me?

**Comment by QAZIMAAZARSHAD** [comment]
First and correct PR will be accepted.

**Comment by satyampgt4** [comment]
@K-jais @techabhi08  any update...?

**Comment by K-jais** [comment]
I am working on it . I will make its PR in next 2-3 days
