### ISSUE TITLE
Redesign contact page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#30]

**Comment by K-jais** [comment]
Please assign this issue to me. I will redesign the contact us section and will also add the contact us form with some links to the social media.

**Comment by QAZIMAAZARSHAD** [comment]
@K-jais I will assign you this issue when DevIncept will commence from 10th July.

**Comment by K-jais** [comment]
Ok sir.

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD sir can you please assign this issue to me?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD sir can you please assign this issue to me?

Already assigned to others.

**Comment by QAZIMAAZARSHAD** [comment]
Do a few more changes I suggested then make a new PR.
