### ISSUE TITLE
"Appliances" go to next line when you hover over "TV and Appliances" button 

### ISSUE THREAD

**Issue by GaurPeeyush** [QAZIMAAZARSHAD/Apni-Dukaan#32]
## Describe the bug
A clear and concise description of the bug is "Appliances" go to the next line when you hover over the "TV and Appliances" button.

## To Reproduce
1.  Make changes to index.html

## Expected behavior
"TV and Appliances should come in single line whenever anyone hovers over that button.

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open.
