### ISSUE TITLE
To add booking/purchase page for online card payment

### ISSUE THREAD

**Issue by aishwaryas15** [QAZIMAAZARSHAD/Apni-Dukaan#34]
A better web design for placing order & addition of contact page,account login page

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DCP will start from 10th July.

Also, issues to add a contact page, a login page is already open and it is always better to open different issues for a particular task rather than doing it all in one.

**Comment by aishwaryas15** [comment]
so shall I continue with placing the order/booking page?

**Comment by QAZIMAAZARSHAD** [comment]
> so shall I continue with placing the order/booking page?

Yes, you can start working on it but don't make PR till tomorrow.

**Comment by QAZIMAAZARSHAD** [comment]
@aishwaryas15 any updates?

**Comment by aishwaryas15** [comment]
website link?

**Comment by QAZIMAAZARSHAD** [comment]
Deploy your website anywhere like GitHub pages, repl.it, netify, etc. then share link.

**Comment by aishwaryas15** [comment]
Sure I'll send the link soon.Thank you.
