### ISSUE TITLE
Making the footer attractive and linking its items

### ISSUE THREAD

**Issue by aakankshabhende** [QAZIMAAZARSHAD/Apni-Dukaan#35]

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DCP will start from 10th July.

**Comment by aakankshabhende** [comment]
Okay @QAZIMAAZARSHAD sir

**Comment by shindesuyog** [comment]
I would like to work on footer. please assign this to me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on footer. please assign this to me @QAZIMAAZARSHAD

Look for some other issues. This will be assigned to @aakankshabhende.

**Comment by priyanshi5** [comment]
Please assign this issue to me under DCP.

**Comment by priyanshi5** [comment]
I would like to work on this issue under DCP.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue under DCP.

Already assigned look for some other issues.

**Comment by aakankshabhende** [comment]
Can you please send social links of Apni Dukaan @QAZIMAAZARSHAD sir as I want to link them in footer.

**Comment by QAZIMAAZARSHAD** [comment]
@aakankshabhende this is just a demo website.
Social links do not exist, just link them to social pages.

**Comment by Sia0** [comment]
Hi can i contribute to this if no one was assigned?

**Comment by aakankshabhende** [comment]
Please assign this issue to someone else @QAZIMAAZARSHAD sir

**Comment by QAZIMAAZARSHAD** [comment]
What happened @aakankshabhende you had already made the PR?
