### ISSUE TITLE
Create a Better and responsive "Contact Us" page along with form submission option.

### ISSUE THREAD

**Issue by i-priyanshu** [QAZIMAAZARSHAD/Apni-Dukaan#37]
I Can improve the look and feel of the contact us page as well give user a form to fill , which will be directed to admin's email.

It would be really great if you could assign this issue to me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DCP will start from 10th July.
