### ISSUE TITLE
Can we use firebase for server and add material theme to the website? 

### ISSUE THREAD

**Issue by i-priyanshu** [QAZIMAAZARSHAD/Apni-Dukaan#39]
## For server : 
I have worked with `Firebase`, `MongoDB` and `MySQL`  for databases, and among them, Firebase provides a very smooth authorisation process(including third-party API integration) than the others along with `Firestore` too.

## For theme:
just a personal opinion, but the mono-themed websites looks way better than the ones which aren't.  we can use our own custom theme too. For starters, we can use material theme for the same.

**Comment by QAZIMAAZARSHAD** [comment]
Sure go ahead.

I will assign you this issue when DCP will start from 10th July.

**Comment by satyampgt4** [comment]
@i-priyanshu any update ..?

**Comment by i-priyanshu** [comment]
It may take time more than i thought , you can assign it to other person , if they are willing to do.
