### ISSUE TITLE
Can create a seperated catogary part for website 

### ISSUE THREAD

**Issue by tany1014** [QAZIMAAZARSHAD/Apni-Dukaan#45]
such as other shopping app we can create a catogary seccion in a creative and decent way @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@tany1014 didn't get it, can you explain your idea.

**Comment by tany1014** [comment]
For example we can take flipcart or Amazon they have separate section
For clothes , mobile and many more @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Yaa sure.

Make separate sections on the home page.
