### ISSUE TITLE
Cards in mobile section

### ISSUE THREAD

**Issue by Amrutha1101** [QAZIMAAZARSHAD/Apni-Dukaan#47]
## Is your feature request related to a problem? Please describe.
As you can see in mobile section, I will make these into separate cards

![Screenshot (141)](https://user-images.githubusercontent.com/63070698/125156661-45ec9f80-e184-11eb-9f3b-6ece94add6ae.png)

**Comment by QAZIMAAZARSHAD** [comment]
@Amrutha1101 this issue is already open before opening any issue make sure that no other similar issue is open.
