### ISSUE TITLE
Redesign offers slideshow 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#5]
![Screenshot (177)](https://user-images.githubusercontent.com/56196640/123572691-3bc4bb80-d7ea-11eb-92e6-cc8112a2f860.png)

**Comment by K-jais** [comment]
Please assign this issue to me. I have added these types of carousels or slideshows in e-commerce and food delivery projects.

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DevIncept will commence from 10th July.

**Comment by K-jais** [comment]
Ok sir.

**Comment by tjanhvi** [comment]
I would like to do this work. 
Please assign me this issue.

**Comment by tjanhvi** [comment]
> I would like to do this work.
> Please assign me this issue.

okay :)
