### ISSUE TITLE
Design a new creative about us page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#52]

**Comment by navyasrisangem** [comment]
Please assign this issue to me @QAZIMAAZARSHAD

**Comment by shivaprasadyanala** [comment]
@QAZIMAAZARSHAD  is there slack channel to discuss if there share the link.

**Comment by shivaprasadyanala** [comment]
@QAZIMAAZARSHAD  assign this task to me.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD assign this task to me.

This issue is already assigned.

**Comment by navyasrisangem** [comment]
https://drive.google.com/file/d/1gaA-x-BQEoP0lYzIvWP5Tue9ocnHwezD/view?usp=drivesdk    
   Is this ok sir @QAZIMAAZARSHAD ?

**Comment by QAZIMAAZARSHAD** [comment]
Increase the width. There is plenty of space on the sides.

Also, remove the horizontal scroll bar.

**Comment by navyasrisangem** [comment]
Okay.

**Comment by QAZIMAAZARSHAD** [comment]
Correct everything and make new PR

**Comment by ChristineLeong** [comment]
@QAZIMAAZARSHAD Hi, mat i get this task?

**Comment by tjanhvi** [comment]
Please assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign me this issue.

I assigned you another issue.

**Comment by QAZIMAAZARSHAD** [comment]
@ChristineLeong careers, press these are different things don't include it in about us page.
