### ISSUE TITLE
Add show/hide password feature 

### ISSUE THREAD

**Issue by mdinesh124** [QAZIMAAZARSHAD/Apni-Dukaan#54]
## Describe the solution you'd like
I would add show or hide password feature in login.html page.

**Comment by mdinesh124** [comment]
Please assign me this issue. I would work on it.

**Comment by QAZIMAAZARSHAD** [comment]
@mdinesh124 login page has not been created yet.
Also an issue to redesign sign up page is already open.

**Comment by mdinesh124** [comment]
![Screenshot (274)](https://user-images.githubusercontent.com/79132253/125169159-85d47680-e1c6-11eb-903e-7e45a47b7604.png)

I supposed to add in this page.

**Comment by QAZIMAAZARSHAD** [comment]
This page is supposed to be redesigned so no use.

**Comment by mdinesh124** [comment]
Ok
