### ISSUE TITLE
Redesign homepage.

### ISSUE THREAD

**Issue by tjanhvi** [QAZIMAAZARSHAD/Apni-Dukaan#59]
Please assign me this issue.

**Comment by satyampgt4** [comment]
@tjanhvi please describe your idea how will you redesign

**Comment by Rahul-Bhati** [comment]
please assign me this issue i add bootstrap and make homepage look cool.

**Comment by QAZIMAAZARSHAD** [comment]
@tjanhvi similar issues are already open.
