### ISSUE TITLE
Create a separate "Deals of the Day" page and remove deals section from home page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#6]

**Comment by Swastik1710** [comment]
Please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
@Swastik1710  I will assign you this issue when DevIncept will commence from 10th July.

**Comment by tjanhvi** [comment]
I would like to do this .
Please assign me this issue.

**Comment by satyampgt4** [comment]
> I would like to do this .
> Please assign me this issue.

@tjanhvi go ahead

**Comment by satyampgt4** [comment]
@Swastik1710 ask first so he will be assigned if he will unable to solve issue @tjanhvi you will be assigned next

**Comment by tjanhvi** [comment]
> @Swastik1710 ask first so he will be assigned if he will unable to solve issue @tjanhvi you will be assigned next

okay :)

**Comment by Swastik1710** [comment]
Hey @QAZIMAAZARSHAD , I'm thinking of adding Deals of the Day tab on the navbar in place of Offers.
It would be better imo.
What do u say ?

**Comment by QAZIMAAZARSHAD** [comment]
> Hey @QAZIMAAZARSHAD , I'm thinking of adding Deals of the Day tab on the navbar in place of Offers.
> It would be better imo.
> What do u say ?

Yaa better.
But don't disturb the navbar.

**Comment by Swastik1710** [comment]
So shall I remove Offers and add Deals of the Day ?

**Comment by Swastik1710** [comment]
Here's the new Deals of the Day page with the modified navbar

![Screenshot 2021-07-12 094325](https://user-images.githubusercontent.com/71871571/125230112-cda5eb80-e2f5-11eb-9ae5-d48e1928a419.jpg)

**Comment by QAZIMAAZARSHAD** [comment]
Make deals of the day page stylish.

Refer to some websites and apply better design.

**Comment by Swastik1710** [comment]
I think this one's looking good.

![ezgif com-gif-maker(3)](https://user-images.githubusercontent.com/71871571/125233196-b669fc80-e2fb-11eb-8653-20969cbb66c0.gif)

**Comment by QAZIMAAZARSHAD** [comment]
Add few more cards.

**Comment by Swastik1710** [comment]
Yeah I'll add one more row

**Comment by satyampgt4** [comment]
try to add border in each card 🤔 may be it will look good

**Comment by Swastik1710** [comment]
How's this

![Screenshot 2021-07-12 120900](https://user-images.githubusercontent.com/71871571/125242269-17003600-e30a-11eb-9019-e9167aa0aa64.jpg)

**Comment by QAZIMAAZARSHAD** [comment]
Cool.

Is the time dynamic?
If not make it, also after reaching 0 timers should restart.
Also, all times are same, make each different.

**Comment by Swastik1710** [comment]
Yeah it's dynamic.
As of now, I've set it as such that it shows "Expired" once the timer reaches 0.
I'll change it to reset as you said.

**Comment by Swastik1710** [comment]
I've set the expiry date of 1 year later.

![Screenshot 2021-07-12 123035](https://user-images.githubusercontent.com/71871571/125244518-0dc49880-e30d-11eb-9e62-4de3fa06c9f0.jpg)

**Comment by QAZIMAAZARSHAD** [comment]
@Swastik1710 these number of days are too  much for an offer.

7 days, 3 months, 1 month, 16 days is fine.

**Comment by tjanhvi** [comment]
> @Swastik1710 ask first so he will be assigned if he will unable to solve issue @tjanhvi you will be assigned next

okay
