### ISSUE TITLE
Create a page for Book 

### ISSUE THREAD

**Issue by satyampgt4** [QAZIMAAZARSHAD/Apni-Dukaan#60]
## Is your feature request related to a problem? Please describe.
Create a page for Books

**Comment by Abhishek-Sahoo** [comment]
Yes I can work on the Books page.

**Comment by QAZIMAAZARSHAD** [comment]
@Abhishek-Sahoo any updates?

**Comment by Abhishek-Sahoo** [comment]
@QAZIMAAZARSHAD @satyampgt4. Due to my personal problem I am unable to work on the task. You may unassign me or allow me more 2 days. 
Sorry for inconvenience

**Comment by QAZIMAAZARSHAD** [comment]
Ok, you have 2 more days.

Don't take too long this time.

**Comment by Abhishek-Sahoo** [comment]
Thank you.

**Comment by Abhishek-Sahoo** [comment]
Is there any form to be filled after my PR is merged. It was once told by Devincept team.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Is there any form to be filled after my PR is merged. It was once told by Devincept team.

Yes, check the description in the slack channel.
