### ISSUE TITLE
The email id field on Sign Up page is a text type field

### ISSUE THREAD

**Issue by mrunmayee9601** [QAZIMAAZARSHAD/Apni-Dukaan#64]
On the Sign Up Page when we enter the email id without the @ extension also it is getting accepted .
So I would like to change the email id field type.
@QAZIMAAZARSHAD Pls assign this issue to me!

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
> Please do assign this to me.

Already assigned.
I think you are assigned top other issues as well finish them first.

**Comment by purohitmansi** [comment]
No

**Comment by mayank-wadhwa-git** [comment]
Please assign this to me

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign this to me

This issue is already assigned.
