### ISSUE TITLE
update pull_request_template

### ISSUE THREAD

**Issue by satyampgt4** [QAZIMAAZARSHAD/Apni-Dukaan#66]
In pull_request_template.md
Change
`Issue Number`

with 
`Fixes #(issue number) `
so that issue automatically get close on successful merge of PR

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD Assign this to me, please.

**Comment by manasb15** [comment]
@satyampgt4 Thanks for suggesting this update!
