### ISSUE TITLE
Create forget password validation in sign up page.

### ISSUE THREAD

**Issue by pravleen17** [QAZIMAAZARSHAD/Apni-Dukaan#67]
Feature addition to sign up page.
Add forget password validation which will be very useful

**Comment by satyampgt4** [comment]
@pravleen17 do you want to work on ..?

**Comment by Sanju-github002** [comment]
I want to work on this issue !!

**Comment by purohitmansi** [comment]
I would like to work on this.
Please do assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this.
> Please do assign this to me.

Already assigned.

**Comment by purohitmansi** [comment]
Okay
