### ISSUE TITLE
Create a separate page of TV & Electric appliances

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#7]

**Comment by SanthoshPatkar** [comment]
Please assign this issue to me

**Comment by QAZIMAAZARSHAD** [comment]
@SanthoshPatkar I will assign you this issue when the DCP will start from 10th July.

**Comment by satyampgt4** [comment]
@SanthoshPatkar any updates...?

**Comment by SanthoshPatkar** [comment]
@satyampgt4 almost done.. within 2-3 days I'll send PR

**Comment by navya-Singla-1-3-0-9** [comment]
Can you please assign this issue to me if it is still open?

**Comment by shrutimeg** [comment]
Assign this issue to me so I can design this page.

**Comment by QAZIMAAZARSHAD** [comment]
> Assign this issue to me so I can design this page.

@navya-Singla-1-3-0-9 is working on this issue.
