### ISSUE TITLE
Remove Checklist point from pull_request_template.md

### ISSUE THREAD

**Issue by manasb15** [QAZIMAAZARSHAD/Apni-Dukaan#73]
This point in the checklist :

(I have added my name in the contributors list at the end of README.md file.)

is obsolete. So it is wise to remove it.

@QAZIMAAZARSHAD please assign this to me under DCP21

**Comment by satyampgt4** [comment]
use correct title for issue

**Comment by manasb15** [comment]
@satyampgt4 This works or should I be more specific?
