### ISSUE TITLE
Create a better design of website

### ISSUE THREAD

**Issue by Sanju-github002** [QAZIMAAZARSHAD/Apni-Dukaan#75]
I add some CSS change to make website more neat and clear. Change in offer box and in color of footer.
<img width="953" alt="Screenshot 2021-07-12 130906" src="https://user-images.githubusercontent.com/78341083/125249071-6fd3cc80-e312-11eb-89f3-359d3186281c.png">
<img width="960" alt="Screenshot 2021-07-12 130930" src="https://user-images.githubusercontent.com/78341083/125249078-7104f980-e312-11eb-92e5-f94084a83bff.png">

**Comment by satyampgt4** [comment]
@Sanju-github002 check this #6

if you have any other idea please let us know

**Comment by Sanju-github002** [comment]
okkk sir
