### ISSUE TITLE
I want to change the UI of the webpage. 

### ISSUE THREAD

**Issue by Subham-Satapathy** [QAZIMAAZARSHAD/Apni-Dukaan#84]
The UI of the website is looking too old style and I want to give a modern look to the home page specially.

**Comment by Subham-Satapathy** [comment]
Thank you.

**Comment by Subham-Satapathy** [comment]
Can I change the logo?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I change the logo?

Yaa you can do all the changes to improve the design.
