### ISSUE TITLE
Tab name and link is different

### ISSUE THREAD

**Issue by PrathmeshMutke** [QAZIMAAZARSHAD/Apni-Dukaan#87]
## Describe the bug
As mouse cursor scrolls to **offers** tab on home page it gives the link of **deals** 
while other tabs are having same name and links 
## To Reproduce
1. both should be same

**Comment by QAZIMAAZARSHAD** [comment]
Under DCP?

**Comment by AdityM1** [comment]
DCP 21

**Comment by PrathmeshMutke** [comment]
DCP 21

**Comment by dilroseR** [comment]
can i work on this?

**Comment by QAZIMAAZARSHAD** [comment]
> can i work on this?

This is already assigned look for some other issues.

**Comment by satyampgt4** [comment]
@PrathmeshMutke any update...?

**Comment by dilroseR** [comment]
if it is not done then can i take up this?
