### ISSUE TITLE
Change title bar text to Apni Dukaan and add logo in title bar

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Apni-Dukaan#9]

**Comment by Swastik1710** [comment]
Please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when DevIncept will commence from 10th July.
 
 Till then don't request any issue to be assigned.

**Comment by Swastik1710** [comment]
Yeah sure.
Eagerly waiting  for the program to get started.

**Comment by sujay2306** [comment]
can yu assign me please

**Comment by QAZIMAAZARSHAD** [comment]
> can yu assign me please

Look for issues that are not assigned to anyone.
